name: Run Shell Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest  # Or specify other OS if needed

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the shell script
      - name: Run the shell script
        run: ./run2.sh
