name: Python Application with Gunicorn Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install Gunicorn and Flask
      run: |
        pip install gunicorn flask
    
    - name: Start Gunicorn
      run: |
        # Start Gunicorn to serve app6.py
        gunicorn --bind 0.0.0.0:8000 app6:app
